### ISSUE TITLE
mask and subtype field null on plaidlink response on ios sdk

### ISSUE THREAD

**Issue by vanderpol2** [plaid/link#294] opened 2019-01-28 07:45 UTC
### A detailed description of the steps to reproduce the issue

- The select account is enabled on dashboard. After successful connection of accounts in the plaid link of ios Linkit sdk v1.1.14, the onSucess handler has all the accounts selected response but the mask and subtype field is null which is not the behavior we see in the plaid link implementation in other environments.
- On checking the web view, the mask and subtype field is returned. Also the Linkit sdk returns actual value of these two fields in sandbox. 

### What you expected to see?
```
"account": {
id = jhdfjsdhkjhk13j21h3;
mask = "0000";
name = "CREDIT CARD";
subtype = credit card;
type = credit;
}
```

### What you saw instead?
```
"account": {
id = jhdfjsdhkjhk13j21h3;
mask = "\<null\>";
name = "CREDIT CARD";
subtype = unknown;
type = credit;
}
```

***

| Name            | Value |
|-----------------|-------|
| Link `env`      |  development     |
| LinkKit version |   1.1.14    |
| iOS version     |    all   |
| iOS device      |      all |

***

#### List of used 3rd party libraries (CocoaPods):

* [Plaid](https://cocoapods.org/pods/Plaid)

**Comment by afh** [comment] 2019-01-28 08:51
Thank you for reporting @vanderpol2, I'll investigate.

**Comment by vanderpol2** [comment] 2019-01-28 16:15
Any clues regarding the issue?

**Comment by afh** [comment] 2019-01-28 17:11
Yes, @vanderpol2. The `unknown` subtype is related to the type of the account, i.e. for `savings` and `checking` accounts the subtype should be properly handed off, can you confirm?

Regarding the `null` account mask I have to dig deeper.

**Comment by afh** [comment] 2019-01-28 17:30
@vanderpol2 If you could provide a `request_id` from the metadata handed off to the delegate when the account mask is `null` that would be helpful.

**Comment by vanderpol2** [comment] 2019-01-29 02:58
@afh , The same account provides correct information when Plaid Link WebView is used. The request id is CgRViN4uoolr1o9

![image](https://user-images.githubusercontent.com/35971367/51881093-f645ff00-23a1-11e9-83a2-fdfc95592ce2.png)

**Comment by vanderpol2** [comment] 2019-01-29 16:20
@afh, is this bug with Link Kit ? Any progress? It’s something very urgent to us. Kindly respond.

**Comment by afh** [comment] 2019-01-29 19:01
Hi @vanderpol2,
thank you for providing the `request_id` it has been helpful in the investigation of what is causing the inconsistency in the handoff data between Link Web and LinkKit you're observing.

To answer your questions:
- The `account_subtype` being `unknown` instead of `credit card` is an inconsistency in LinkKit and a fix for this will be available with the next version of LinkKit in 1-2 weeks from now.
- Regarding the cause of the `account_mask` being `null` instead of `0000`, we are actively investigating this issue, however believe there is an issue with our Chase integration. Will follow up with any progress.

**Comment by jeffreyjackson** [comment] 2019-01-29 22:40
This is great news, my client is experiencing the same issue.  Thank you for the follow up.

**Comment by pbernasconi** [comment] 2019-01-30 00:23
@jeffreyjackson could you share light on whether you're experience both issues or just one of the above?

**Comment by vanderpol2** [comment] 2019-01-30 00:43
Thank you @afh.
I assume that the next releaae will solve both of these cases.

**Comment by jeffreyjackson** [comment] 2019-01-30 14:53
@pbernasconi the issue I'm experiencing is that iOS Link does not show the same institutions as Web Link.  For example, Republic Bank shows up for weblink but not iOS link.

**Comment by vanderpol2** [comment] 2019-01-31 15:59
Why is that requests made from iOS devices are different from that of Android?
The Plaid webview when implemented at iOS doesn’t even have “mask” key in the response. Can you guide us?

**Comment by pbernasconi** [comment] 2019-01-31 21:33
@jeffreyjackson it seems you're seeing a different issue – could you open a separate github issue with:
- link_session_id
- the institution ID you should be expecting
- the Link iOS version
- any other details that might be helpful

**Comment by pbernasconi** [comment] 2019-01-31 21:37
@vanderpol2 – the Plaid Link iOS SDK is a separate SDK built in native Objective C whereas the Link Webview SDK is written in JS & HTML. We aim to keep both SDKs always up to date and unified in the user experience.

We're actively fixing the issue you reported and should be available in the next release

**Comment by vanderpol2** [comment] 2019-02-01 03:51
@pbernasconi , @afh We are also facing a new issue with iOS device. When connected to Bank using Webview in iOS, the "mask" field is not present whereas it was there with LinkKit but the value was null. Hence, we are trapped in a maze where all our business logic are failing. Can you look into this issue and help us as soon as possible.
Here is the response to iOS using Webview:
![image](https://user-images.githubusercontent.com/35971367/52101673-c34f7580-2604-11e9-8618-92950e2b7a42.png)

**Comment by afh** [comment] 2019-02-05 13:04
Hello @vanderpol2,
quick update that [LinkKit version 1.1.15](https://github.com/plaid/link/releases/tag/ios%2F1.1.15) has been released including a fix for the account subtype metadata. Please update your version of LinkKit and verify your issue is addressed.

**Closed** 2019-02-05 14:11 UTC
Labels: bug, ios

**Comment by vanderpol2** [comment] 2019-02-06 04:01
@pbernasconi and @afh , requesting you to please provide me the update on the mask number. Is that issue addressed and fixed?

**Comment by pbernasconi** [comment] 2019-02-06 23:02
Hi @vanderpol2 – looking deeper into the issue, it seem this is an error specific to our integration.

Your best path to finding a resolution would be to open a Support ticket via the [Plaid Dashboard](https://dashboard.plaid.com/support/new) which our Support team can help dig in deeper!

**Comment by jeffreyjackson** [comment] 2019-02-13 17:06
@pbernasconi link 1.1.5 fixed my issue

**Comment by afh** [comment] 2019-02-13 17:32
Thanks for letting us know @jeffreyjackson.
