### ISSUE TITLE
Add callback to Don't see my bank in the list

### ISSUE THREAD

**Issue by vikmeup** [plaid/link#167] opened 2017-05-23 07:26 UTC
Is there a way to have a callback for `Don't see my bank in the list`? I would like to have custom action to enter routing/account number.

**Comment by pbernasconi** [comment] 2017-05-24 18:01
Thanks for raising this issue @vikmeup – to answer your question directly: This is definitely a feature that we plan on adding to Link soon.

Currently, the best approach is to use the `onExit` handler to redirect your users to an account/routing flow. We will be sure to update this thread when this feature is available however, so stay tuned for updates!

**Comment by pbernasconi** [comment] 2017-05-24 18:08
Closing this as duplicate of https://github.com/plaid/link/issues/61 - and will keep #61 up to date

**Closed by pbernasconi** 2017-05-24 18:08 UTC
Labels: feature request, planned feature

**Comment by michaelckelly** [comment] 2017-06-15 02:28
@vikmeup - Quick update here, the [`onExit` callback][1] now supports an `institution_not_found` status. This is returned when the user unsuccessfully searches for an institution and clicks a "Don't see your bank?" prompt!

[1]: https://plaid.com/docs/api/#onexit-callback

**Comment by vikmeup** [comment] 2017-06-15 05:33
@michaelckelly does it only happens when user search for that bank? or also when press on `Don't see your bank` in default state?
