### ISSUE TITLE
Empty Verify your identity screen

### ISSUE THREAD

**Issue by artemmihelson** [plaid/link#161] opened 2017-05-04 18:17 UTC
Hi,

I use development environment and get empty screen on Verify your identity step (see the screenshot). Also random taps and long taps on the screen gave me some pictures on the screen which can’t be tapped.

Could you please check this as soon as possible.
![simulator screen shot may 4 2017 1 49 22 pm](https://cloud.githubusercontent.com/assets/1292542/25718494/0332db66-310f-11e7-9b85-941583efa59d.png)
![image uploaded from ios](https://cloud.githubusercontent.com/assets/1292542/25718508/0b104e04-310f-11e7-9216-a74bf42d67d5.jpg)

**Comment by afh** [comment] 2017-05-04 18:52
@artemmihelson Thanks for the report, we're looking into it.

**Comment by artemmihelson** [comment] 2017-05-08 16:42
@afh could you please provide some estimates on when this will be fixed. This is quite urgent bug for me, since it blocks the release.

**Comment by pbernasconi** [comment] 2017-05-08 16:45
@artemmihelson The Link team is looking into this issue this week as a high-pri item! 

We haven't been able to reproduce the bug you're seeing yet however, so if you could provide info regarding device, os version, etc, that would go a long way to help us debug the issue. Thanks!

**Comment by artemmihelson** [comment] 2017-05-08 16:48
@pbernasconi Hi,

I have reproduced this issue on iPhone 5s, and iPhone 7 emulator, the latest iOS version. As I have mentioned, I have used development environment.

**Comment by artemmihelson** [comment] 2017-05-08 17:29
@pbernasconi Looks like you have a web view with Google anti bot system on this screen. But it seems it has wrong layout.

**Comment by afh** [comment] 2017-05-08 20:10
@artemmihelson Thank you for the information.

Since we are unable to reproduce the issue you are observing I have further questions/requests that could help in identifying the cause of the layout issue:

* Can you please send screenshots of the [**Debug View Hierarchy**](https://developer.apple.com/library/content/documentation/DeveloperTools/Conceptual/debugging_with_xcode/chapters/special_debugging_workflows.html) view in Xcode that also shows the **Size Inspector** (on the far right) for the `WKWebView` and its `superview` (see sample below).
* Is any part of the screen scrollable? If yes which? A screenshot to illustrate that would be useful.
* Additionally please provide any other information that you think would be helpful in reproducing the issue.

<img width="1176" alt="gh-161-debug-view-hierarchy" src="https://cloud.githubusercontent.com/assets/16507/25822914/90ee1136-343a-11e7-94bd-b2d4e7c0580e.png">

**Comment by afh** [comment] 2017-05-11 17:29
Hello @artemmihelson we have found some potential causes of the issue and would like to make sure we are including changes that address the issue you are seeing.
Any chance of providing the information we requested? It would be very helpful, thanks!

**Comment by artemmihelson** [comment] 2017-05-11 17:47
Hi @afh, sorry for delayed response.

Here is the info you requested:

![screenshot at may 11 20-34-30](https://cloud.githubusercontent.com/assets/1292542/25963300/78d38f08-3689-11e7-8db9-70ad6cf588e8.png)
![screenshot at may 11 20-31-48](https://cloud.githubusercontent.com/assets/1292542/25963301/790f9552-3689-11e7-9af3-94087c2be821.png)

Below are screenshots of the scrollable part:
![img_2143](https://cloud.githubusercontent.com/assets/1292542/25963571/6d70b518-368a-11e7-9736-076798aa5648.PNG)
![img_2142](https://cloud.githubusercontent.com/assets/1292542/25963572/6da1478c-368a-11e7-9141-ffa8c8c822c5.PNG)

**Comment by afh** [comment] 2017-05-11 18:29
@artemmihelson Thank you for taking the time and providing the requested information, this helps us move into the right direction with our efforts.

**Comment by artemmihelson** [comment] 2017-05-11 20:29
@afh do you have any estimations on when issue could be fixed? Thanks.

**Comment by artemmihelson** [comment] 2017-05-17 07:02
@afh any updates?

**Comment by afh** [comment] 2017-05-17 07:38
Hello @artemmihelson,
unfortunately I do not have an estimation when this could be fixed.

With the information you provided the issue seems to be within the HTML, but we are still unable to reproduce it; even when setting `-AppleLanguages "(ru)" -AppleLocale "uk_UA"` (as recommended by [Apple's Internationalization and Localization Guide](https://developer.apple.com/library/content/documentation/MacOSX/Conceptual/BPInternational/TestingYourInternationalApp/TestingYourInternationalApp.html)). This makes it hard to find a fix, so if you have any further information that you think could help, we'd greatly appreciate knowing about it.

Additionally we are evaluating a completely different solution to the problem where a HTML based validation is only a fallback.

**Comment by artemmihelson** [comment] 2017-05-19 13:32
Hi @afh 

I don't think that language affects somehow, since I have the same result in english interface as well.

Please take a look at the following screenshot, seems like selected (on screenshot) view is mispositioned:

![screenshot at may 19 16-31-23](https://cloud.githubusercontent.com/assets/1292542/26249840/b7c3b508-3cb0-11e7-86d0-b239c5815e5f.png)

**Comment by artemmihelson** [comment] 2017-05-19 13:38
In addition:

![screenshot at may 19 16-37-49](https://cloud.githubusercontent.com/assets/1292542/26250058/8c4365ee-3cb1-11e7-8e28-751b6ef4e659.png)

**Comment by afh** [comment] 2017-05-19 15:06
@artemmihelson Thanks for the additional screenshots, this will be helpful as we dig deeper to find what is causing the offset, which interestingly is half the width (X = W / 2) and half the size (Y = H / 2).

**Comment by artemmihelson** [comment] 2017-05-19 15:11
Hi @afh 

I have made some researches. When I create empty project, everything goes smooth. 

So that made me think that we use something in our project that potentially could cause this issue. 
We use DrawerController cocoapod in our project to display sidebar menu. I don't know for sure, but maybe this lib could cause this issue.

What do you think of this?

**Comment by artemmihelson** [comment] 2017-05-19 15:17
Hi @afh 

Yep, this one.

**Comment by afh** [comment] 2017-05-19 17:31
@artemmihelson Any chance you could provide a test project using DrawerController and LinkKit that illustrates how you use the two?

**Comment by artemmihelson** [comment] 2017-05-19 17:34
@afh this will take a time, but I'll do.

**Comment by afh** [comment] 2017-05-19 17:45
@artemmihelson Much appreciated! 👍 

I'd like to point out that the README of DrawerController states, that it
> […] is currently a work in progress and has not been thoroughly tested. Use at your own risk.

**Comment by afh** [comment] 2017-05-30 17:34
Hi @artemmihelson have you been able to make progress on a test project that illustrates the observed issue when LinkKit is used in combination with the DrawerController Cocoapod?

**Comment by artemmihelson** [comment] 2017-06-08 17:28
Hi @afh, yes, I have been able to create a test project, but project with only Plaid Link and Drawer controller doesn't seem to have this issue... So I got stuck again.

**Comment by afh** [comment] 2017-06-08 17:59
Hi @artemmihelson thanks for following up!

I will close this issue for now and kindly ask you to open a new issue once the cause has been narrowed down and there is a test project available which demonstrates the odd behaviour that has been observed.

**Closed by afh** 2017-06-08 17:59 UTC
Labels: bug, ios
