### ISSUE TITLE
Link UI not drawing properly on Android

### ISSUE THREAD

**Issue by colinloretz** [plaid/link#52] opened 2015-10-15 18:03 UTC
Has anyone else seen this issue with Android? The UI is flickering with the textfield cursor.

I've confirmed this on Lollipop and Marshmallow.

The keyboard is also getting in the way of the UI, whereas in iOS, the webview moves with the keyboard so you can see both the username and password fields. This might be something we will have to handle on our end but thought worth mentioning.

![screenshot_20151015-105901_720](https://cloud.githubusercontent.com/assets/36084/10522798/056c3d70-732c-11e5-94c8-c07ccca4e28a.png)

**Comment by c316** [comment] 2015-10-15 18:06
Oh, yes it is pretty bad in my app too. I figured that was because this
isn't designed for mobile.

**Comment by LDubya** [comment] 2016-01-29 18:38
Same issue. Absolutely horrible on my app. Utterly unusable on Android.

**Comment by michaelckelly** [comment] 2016-01-29 19:52
@LDubya -

I'm sorry that you're having trouble. Could you share some additional details about how you're using Link on Android (such as OS version, browser, whether it's embedded in an app, etc.). That will help us investigate faster!

**Comment by LDubya** [comment] 2016-01-31 18:13
Hey @michaelckelly, thanks for the quick response. Yes it's embedded in the app. Android version: Lollipop, although the guy above also confirmed it on Marshmallow. Any suggestions?

**Comment by ericnjung** [comment] 2016-02-15 19:44
Hi @michaelckelly , we are experiencing the same issue as noted above, curious if there is any findings/ solution yet.  Thank you!

**Comment by damianesteban** [comment] 2016-02-17 15:37
@michaelckelly has there been any update on this?

**Comment by michaelckelly** [comment] 2016-02-22 23:42
@damianesteban @ericnjung -

Our Link team is actively working on this - in the meantime, any additional information you can provide would be helpful (i.e. Android version, whether the web view is embedded, frameworks, etc.)

**Comment by damianesteban** [comment] 2016-02-23 01:14
I'm not developing the Android application but I will speak to the developer and get back to you by tomorrow morning.

Thank you.

D Esteban
Lead Developer @ Bracket Factory

**Comment by ericnjung** [comment] 2016-02-23 17:48
Hi @michaelckelly, 

This is the response from our front-end team. Hope this will be helpful.

Android versions- 5 (Lollipop) and 6 (Marshmallow)
Whether the web view is embedded-  Yes. It is embedded.
Framework- Ionic.
 Screenshot 1: The view does not  render properly.
 Screenshot 2: The text fields for Username and password gets jumbled up , whenever one tries to enter Username and password (i.e., when the keyboard comes up).
For android versions (<5) It is working smoothly. Also, there is no problem in iOS.
![screenshot2](https://cloud.githubusercontent.com/assets/15620105/13260906/88421b28-da12-11e5-9f24-d33c16eeebcc.png)
![screenshot1](https://cloud.githubusercontent.com/assets/15620105/13260908/8ca33a3a-da12-11e5-8d49-b7872cb2fbd4.png)

**Comment by jjperezaguinaga** [comment] 2016-02-23 17:48
@colinloretz @c316 @LDubya @ericnjung @damianesteban

Hello there, as @michaelckelly mentioned, we are working on this particular issue; we are aware that Link’s experience could be better on Android platforms, and we have already some leads on how to improve it.

<img width="340" alt="android" src="https://cloud.githubusercontent.com/assets/1128312/13260900/8260fa62-da12-11e5-83bc-f51b38bcd073.png">

While replicating the issue, we noted that Link’s behavior become partially unstable when on top of Webview wrappers (e.g. Cordova). Currently we are working in improving the nature of its web components to avoid this.

In the long term, we will work on appropriate Android native bindings for mobile developers.

**Comment by ericnjung** [comment] 2016-02-23 17:51
Awesome, thank you!

Eric Jung

Gelper, Inc
619.865.3397
eric@gelper.io
www.gelper.io

**Comment by jjperezaguinaga** [comment] 2016-02-23 23:29
@colinloretz @c316 @LDubya @ericnjung @damianesteban

Until we manage to improve the experience on Link, I would recommend anyone that does Ionic+Link integration for front end hybrid applications on Android, to take a look at the [Crosswalk Project](https://crosswalk-project.org/). In many instances using Crosswalk-Lite greatly improved the overall experience, removed some flickering and made the overall transition/animation process faster. Of course, the drawback is that any application using Crosswalk would increase its size, but if it's a blocking factor, might be worth giving it a try as a temporal solution.

![image](https://cloud.githubusercontent.com/assets/1128312/13270185/3a1da0b4-da41-11e5-80ad-d753912da028.png)

If you are familiar with the Ionic CLI, you can do as follows to switch from the default android browser to the Crosswalk one:

**NOTE: This will remove the `platform/android` folder, ensure you don't have any platform specific changes in the folder before executing the following code. For more information about Ionic+Crosswalk, see the following [article](http://blog.ionic.io/crosswalk-comes-to-ionic/) from Ionic's Blog.**

```console
$ ionic browser list #locate crosswalk-lite, or the version you want to setup
$ ionic browser revert android #see previous note
$ ionic browser add crosswalk-lite #overriding system's default webview
$ ionic run android #run application
```

Information about the test environment used:

```
Cordova CLI: 6.0.0
Ionic Version: 1.1.0
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
Node Version: v5.6.0
```

**Comment by LDubya** [comment] 2016-02-24 22:33
> @jjperezaguinaga In the long term, we will work on appropriate Android native bindings for mobile developers.

This wouldn't help us. We use Link with Ionic because we are not native Android developers.

**Comment by jjperezaguinaga** [comment] 2016-02-24 22:58
@LDubya Understood. Please see my comment on setting crosswalk-lite as a temporal solution. We think that most of the issues with Link on Android+Ionic are due our usage of some CSS properties (i.e. transitions, box-shadow) that aren't handled very well by some [versions of Android](https://forum.ionicframework.com/t/ionic-transitions-in-lollipop-are-slow/15486). We are working on improving/changing those for mobile specific releases in the future.

**Comment by damianesteban** [comment] 2016-02-24 23:42
This screenshot was taken on an a device running Android 5.1.1 in an embedded web view, but we have seen this bug on different versions of Android as well:

![plaid_link_bug](https://cloud.githubusercontent.com/assets/4554498/13304895/95e73c18-db25-11e5-8b7b-2ab5979748cb.png)

The app is native.  We have been very loyal customers to Plaid (the iOS version of the app has been out for awhile) and we would very much like to continue to use their service, however we plan to launch the Android app in about a month.

**Comment by jjperezaguinaga** [comment] 2016-02-25 00:08
@damianesteban This a behavior we have detected in some late versions of Android. For the short term, please see my comment earlier about the possibility of integrating crosswalk-lite.

Could you provide us more information about the frameworks/tools you are using to wrap the webview into the native application at support@plaid.com?

**Comment by damianesteban** [comment] 2016-02-25 00:27
Yes I will get back to you concerning that shortly.

Damian Esteban
@estebanrules

**Comment by ericnjung** [comment] 2016-02-25 18:10
Hi Jose,

Thanks for the temporal solution with Crosswalk.  Initial results appear to have resolved the problem, we are waiting to hear back from all of our testers who have experienced this to get more results.

As you mentioned though, due to the increased size of the file from using Crosswalk, this isn’t a great long term solution.  Our file size of the application went from roughly 5 MB to over 24 MB.

Appreciate the help, please keep us updated on efforts to resolve the issue directly within Plaid.

All the best,

Eric Jung

Gelper, Inc
619.865.3397
eric@gelper.io
www.gelper.io

**Comment by LDubya** [comment] 2016-02-28 01:31
Plaid has been approved, but Crosswalk is not. We like to keep the third-party tools we use at a minimum, as you might understand. It's happened before where a third-party platform closed its doors when we needed it the most. We're counting on you. If you want, you could tell us what the issue is here, maybe point to the relevant section of the code-base (it's client-side code, nothing secret anyways) and we can try to contribute a solution.

**Comment by ericnjung** [comment] 2016-03-12 00:41
Hi Plaid!  Curious if you have been able to make any headway on a direct solution for this issue.  The Crosswalk solve is a killer with the increased file size.  Per @LDubya , we would like to keep from having to use another 3rd party.  Any update would be appreciated.  Thank you!

**Comment by jjperezaguinaga** [comment] 2016-03-13 05:14
@ericnjung @LDubya I'm afraid we currently don't have a short term solution with a fixed deadline we can provide. Since we need to trim many of the CSS properties used in Plaid Link only for Android, we need to make sure we don't break other elements of the application. This isn't a quick task due that sole fact.

We know this isn't the answer you were expecting to hear, but we prefer being upfront and honest. We are, however, still working on the issue and will update this issue as soon as we have more solid updates or deadlines to offer. Thank you for your patience!

**Comment by Aea** [comment] 2016-03-30 00:59
This isn't going to be a great solution, but I found that disabling Hardware Acceleration and invalidating the WebView after it's finished loading does the trick. 

Fixes the rendering clipping / weirdness when entering into text input:
`webView.setLayerType(View.LAYER_TYPE_SOFTWARE, null);`

+

Fixes the occasional white screen until scroll issue:
`webView.invalidate();`

It's very very slow, but it's usable.

**Comment by mpk2** [comment] 2016-05-09 04:21
Wondering if there's any progress on this beyond using Crosswalk. Right now we're having the same flickering / keyboard issues as stated before.

**Comment by mpk2** [comment] 2016-10-15 18:45
Bumping this issue as this continues to force our apks to be double their size. Been waiting months for any sort of update on this. We can't use crosswalk-lite due to the fact that it drops support for requirements that we have in our app.

**Comment by pbernasconi** [comment] 2016-10-25 19:07
@colinloretz @c316 @LDubya @ericnjung @damianesteban @Aea @mpk2 

We've been working to overhaul Plaid Link on mobile devices and would appreciate your feedback on the [Link mobile beta][1].

The android exmaple in the `mobile-beta` directory should help get you started with integrating the beta. If you have any further questions - please feel free to continue communication in this issue!

[1]: https://github.com/plaid/link/blob/master/mobile-beta/README.md

**Closed** 2016-10-25 19:11 UTC
