### ISSUE TITLE
Weird sizing issues inside a UIWebView

### ISSUE THREAD

**Issue by RaphiePS** [plaid/link#40] opened 2015-06-26 17:42 UTC
As a stopgap until the iOS bindings come out, I'm prototyping by loading Link in a full-screen UIWebView. Here's the code to set up the web view:

```objective-c
    self.webView = [[UIWebView alloc] init];
    self.webView.delegate = self;
    [self.view addSubview:self.webView];
    [self.webView mas_makeConstraints:^(MASConstraintMaker *make) {
        UIView *topLayoutGuide = (id)self.topLayoutGuide;
        UIView *bottomLayoutGuide = (id)self.bottomLayoutGuide;
        make.top.equalTo(topLayoutGuide.mas_bottom);
        make.bottom.equalTo(bottomLayoutGuide.mas_top);
        make.left.equalTo(self.view);
        make.right.equalTo(self.view);
    }];
    NSURL *url = [[NSBundle mainBundle] URLForResource:@"link" withExtension:@"html"];
    [self.webView loadRequest:[NSURLRequest requestWithURL:url]];
```
and here's the file it loads, `link.html`:
```html
<html>
    <head></head>
    <body>
        <script src="https://cdn.plaid.com/link/stable/link-initialize.js"></script>
        <script type="text/javascript">
            var publicKey = "my-public-key";
            var options = {
                env: "tartan",
                clientName: "my-app",
                key: publicKey,
                product: "connect",
                onLoad: function() {
                    linkHandler.open();
                },
                onSuccess: function(public_token) {
                    window.location.href = "my-app:success:" + public_token;
                },
                onExit: function() {
                    window.location.href = "my-app:exit";
                }
            }
            var linkHandler = Plaid.create(options);
        </script>
    </body>
</html>
```
Here's the weirdness. When I load the page, the sizing is off:
![bad](https://cloud.githubusercontent.com/assets/1091375/8383562/226efec8-1c09-11e5-893a-ce2b92bd909b.png)

When I select a bank and then hit the "back" arrow, it corrects itself and looks great:
![good](https://cloud.githubusercontent.com/assets/1091375/8383557/1e49297c-1c09-11e5-9b07-4bc2613fcb69.png)

I'm guessing this is a weird `UIWebView`-only bug, and will be irrelevant once your iOS bindings come out (hopefully!) soon. But if you know of a quick fix, I'd love to hear it!

**Comment by pbernasconi** [comment] 2015-06-30 20:25
@RaphiePS I can confirm that there is a bug here, and it has been duly fixed in the next release of Link. I'm going to close this issue because it's a duplicate of #38  -- but do know that in the next day or two, when we release the next version live it'll be fixed.

**Closed by pbernasconi** 2015-06-30 20:25 UTC
